export const projectsData = [
  {
    id: 1,
    slug: "ai-audio-transcription",
    title: "AI Audio Transcription",
    category: "Transcription",
    description: "Created clean speaker-labeled transcripts with proper formatting, unclear speech markers, and natural sentence flow.",
    label: "Independent Demo Case Study",
    overview: "A comprehensive demonstration of high-accuracy audio transcription, focusing on multi-speaker environments and challenging audio conditions.",
    objective: "To produce a highly accurate, speaker-labeled transcript that adheres to strict formatting guidelines suitable for AI training datasets.",
    myRole: "Independent Audio Transcription Specialist",
    workflow: [
      "Initial Pass: Complete listen-through for context and overarching themes.",
      "First Draft: Transcribing the audio verbatim while establishing speaker identification.",
      "Timestamping & Tags: Adding [unintelligible] tags and accurate timestamps.",
      "Review & Formatting: Ensuring adherence to strict styling and formatting guidelines.",
    ],
    toolsUsed: ["Express Scribe", "Grammarly", "Google Docs", "Aegisub"],
    sampleOutput: `[00:01:23] Speaker 1: "The primary focus should be on dataset integrity."\n[00:01:28] Speaker 2: "I agree. We need to avoid [unintelligible 00:01:30] at all costs."`,
    qualityChecklist: [
      "99% accuracy rate",
      "Correct speaker identification",
      "No overlapping timestamps",
      "Proper spelling and grammar",
    ],
    finalOutcome: "A pristine, AI-ready transcript demonstrating meticulous attention to detail and ability to parse complex dialogue.",
  },
  {
    id: 2,
    slug: "hindi-english-translation",
    title: "Hindi-English Translation",
    category: "Localization",
    description: "Translated Hindi content into clear, natural English while keeping the original meaning and tone.",
    label: "Independent Portfolio Project",
    overview: "Showcasing nuanced translation skills from Hindi to English, focusing on maintaining cultural context and natural conversational flow.",
    objective: "To translate a diverse set of Hindi texts into English without losing the original tone, idiomatic meaning, or professional context.",
    myRole: "Independent Localization Evaluator",
    workflow: [
      "Source Analysis: Reading the Hindi text to grasp the core message and tone.",
      "Draft Translation: Literal translation while marking idiomatic phrases.",
      "Localization Pass: Adjusting phrasing for natural English readability.",
      "Context Review: Comparing source and target to ensure no semantic loss.",
    ],
    toolsUsed: ["Google Workspace", "Bilingual Dictionaries", "Contextual Research Tools"],
    sampleOutput: `Source (Hindi): "यह परियोजना हमारे लिए बहुत महत्वपूर्ण है।"\nTarget (English): "This project is of critical importance to us."`,
    qualityChecklist: [
      "Semantic accuracy",
      "Cultural appropriateness",
      "Grammatical correctness",
      "Natural readability flow",
    ],
    finalOutcome: "A localized text that reads fluently to English speakers while perfectly preserving the intent of the original Hindi source.",
  },
  {
    id: 3,
    slug: "ai-response-evaluation",
    title: "AI Response Evaluation",
    category: "Evaluation",
    description: "Reviewed AI-generated answers based on accuracy, helpfulness, tone, and instruction-following.",
    label: "Client-Ready Workflow Demo",
    overview: "A rigorous evaluation of large language model (LLM) outputs to assess instruction adherence, factual correctness, and safety.",
    objective: "To critique and score AI responses based on a complex rubric prioritizing helpfulness and harmlessness.",
    myRole: "Independent AI Response Evaluator",
    workflow: [
      "Prompt Analysis: Deconstructing the user prompt to identify all explicit constraints.",
      "Fact-Checking: Verifying the claims made in the AI response against reliable sources.",
      "Tone Assessment: Evaluating the helpfulness, safety, and neutrality of the tone.",
      "Rubric Scoring: Assigning scores and writing detailed justification notes.",
    ],
    toolsUsed: ["AI Evaluation Platforms (Demo)", "Web Research Tools", "Custom Scoring Rubrics"],
    sampleOutput: `Prompt: "Explain quantum computing simply."\nResponse Score: 4/5.\nJustification: "The response is factually accurate and helpful, but uses advanced terminology in paragraph 2 that violates the 'simply' constraint."`,
    qualityChecklist: [
      "Strict adherence to prompt constraints",
      "Factual accuracy verified via external links",
      "Tone matches safety guidelines",
      "Clear, actionable feedback provided",
    ],
    finalOutcome: "Detailed, actionable evaluation data demonstrating the ability to improve LLM alignment through high-quality human feedback.",
  },
  {
    id: 4,
    slug: "content-quality-review",
    title: "Content Quality Review",
    category: "Quality Assurance",
    description: "Improved written content by correcting grammar, structure, clarity, and readability.",
    label: "Demo Case Study",
    overview: "An editorial project focused on elevating standard written content into polished, professional, and highly readable text.",
    objective: "To proofread and edit a batch of articles to improve sentence structure, vocabulary variation, and overall reader engagement.",
    myRole: "Independent Content QA Specialist",
    workflow: [
      "Initial Read: Assessing overall flow and identifying structural issues.",
      "Line Editing: Correcting syntax, grammar, and repetitive vocabulary.",
      "Formatting Check: Ensuring headers, bullet points, and spacing are consistent.",
      "Final Polish: Doing a final read-through for tone and clarity.",
    ],
    toolsUsed: ["Microsoft Excel", "Grammarly Advanced", "Hemingway Editor"],
    sampleOutput: `Before: "The system is fast and it works well for the people using it."\nAfter: "The system delivers rapid performance, ensuring an optimal user experience."`,
    qualityChecklist: [
      "Zero grammatical errors",
      "Consistent formatting applied",
      "Improved readability score",
      "Enhanced professional tone",
    ],
    finalOutcome: "A set of highly refined documents showcasing strict editorial standards and an eye for typographical detail.",
  },
  {
    id: 5,
    slug: "data-annotation-sample",
    title: "Data Annotation Sample",
    category: "Data Annotation",
    description: "Classified text data into categories and reviewed labels for consistency and quality.",
    label: "Independent Portfolio Project",
    overview: "A text classification and tagging exercise designed to simulate the creation of a high-quality supervised learning dataset.",
    objective: "To categorize a large volume of ambiguous text snippets into predefined intents with high inter-rater reliability.",
    myRole: "Independent AI Data Annotator",
    workflow: [
      "Guideline Review: Internalizing the definitions for 15 different classification categories.",
      "Data Labeling: Reading text snippets and assigning primary and secondary tags.",
      "Edge-Case Flagging: Identifying and documenting ambiguous inputs.",
      "QA Review: Self-auditing a random 10% sample of labels for consistency.",
    ],
    toolsUsed: ["Google Sheets", "JSON Validators", "Regex Tools"],
    sampleOutput: `Input: "My screen cracked, how do I fix it?"\nCategory Tag: "Hardware Support"\nSentiment: "Neutral"\nConfidence Score: "High"`,
    qualityChecklist: [
      "Consistent application of taxonomy",
      "Accurate sentiment analysis",
      "Proper edge-case handling",
      "Clean data formatting",
    ],
    finalOutcome: "A meticulously categorized dataset that proves readiness for scaling AI model training operations.",
  },
  {
    id: 6,
    slug: "customer-communication-data-coordination",
    title: "Customer Communication & Data Coordination – CIPT",
    category: "Data Coordination",
    description: "Handled farmer communication, query tracking, data validation, and reporting workflows using Excel, Google Sheets, and structured documentation. Focused on clear communication, issue resolution, and accurate operational data management.",
    label: "Work-Based Project",
    overview: "Managed farmer communication, query handling, follow-ups, and structured data coordination for field-based project operations. Focused on clear communication, issue tracking, documentation, and accurate reporting across multiple districts.",
    objective: "The objective of this project was to support smooth communication between farmers, field teams, and the operations/data team by handling calls, documenting issues, tracking responses, and ensuring collected information was accurate and properly organized.",
    myRole: "Customer Communication & Data Coordination Associate",
    workflow: [
      "Contacted farmers through follow-up calls and collected required project information.",
      "Listened to farmer queries and documented issues clearly in tracking sheets.",
      "Coordinated with the data manager, operations team, and field team for issue resolution.",
      "Maintained structured Excel/Google Sheets records for call status, responses, corrections, and pending cases.",
      "Reviewed collected data for accuracy, missing information, and inconsistencies.",
      "Prepared daily, field visit, and periodic reports for internal review."
    ],
    toolsUsed: [
      "Microsoft Excel",
      "Google Sheets",
      "Google Docs",
      "Phone-based communication",
      "Google Drive",
      "Microsoft Word",
      "Reporting templates"
    ],
    sampleOutput: `Call Status: Answered / Not Answered / Data Denied / Wrong Number\nQuery Type: Data correction / Farmer clarification / Field verification\nAction Taken: Recorded issue and shared with operations team\nFollow-up Status: Pending / Resolved / Escalated\nFinal Update: Farmer response verified and updated in tracking sheet`,
    qualityChecklist: [
      "Verified farmer details before updating records",
      "Checked data for missing or inconsistent entries",
      "Maintained clear status labels for each follow-up",
      "Escalated unresolved issues to the correct team",
      "Updated sheets regularly to avoid duplicate work",
      "Ensured communication remained polite, clear, and professional"
    ],
    finalOutcome: "This project improved the consistency of farmer communication, reduced confusion in follow-ups, and helped maintain accurate operational records. By using structured tracking sheets and clear documentation, the team was able to manage queries, corrections, and reporting more efficiently.",
    skillsDemonstrated: [
      "Customer Support",
      "Verbal Communication",
      "Written Communication",
      "Query Handling",
      "Data Coordination",
      "Documentation",
      "Microsoft Excel",
      "Google Sheets",
      "Problem Solving",
      "Attention to Detail",
      "Remote Collaboration",
      "Process Improvement",
      "Multilingual Communication"
    ]
  }
];
